ci(regression): add test for pyenv shenanigans

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -92,3 +92,34 @@ jobs:
           node --version | grep "16.13.2"
           python --version || grep "3.10.2"
           terraform --version | grep "1.1.5"
+  # Build and run the action from this repo to test full functionality
+  action-regression:
+    name: Test / Regression / setEnv
+    needs: [lint, fast]
+    runs-on: ubuntu-latest
+    env:
+      PYTHON_VERSION: 3.9.13
+    steps:
+      - uses: actions/checkout@v3
+      - name: Install pyenv on hosted runner, unconfigured
+        run: curl https://pyenv.run | bash
+      - name: Create version files
+        run: echo "${PYTHON_VERSION}" > .python-version
+      - name: Setup python
+        uses: actions/setup-python@v4
+      - name: Run action using version files
+        uses: ./
+      - name: Expect a Python failure from pyenv
+        shell: bash
+        run: |
+          # Check versions
+          output="$(python --version)"
+          echo "::debug::python --version: $output"
+          echo "$output" | grep -i "pyenv: version .* not installed" && \
+            {
+              echo "::error:: Expected python --version to work, hit pyenv instead."
+              echo "::debug::$(pyenv versions)"
+              echo "::debug::$(echo "$PATH" | tr ":" "\n")"
+              exit 1
+            }
+          echo "Success!"
